import { Event, TicketOffer, Partner } from './types'

// Mock Partners Data - Hungarian Partners
export const mockPartners: Partner[] = [
  {
    id: 'jegy-hu',
    name: 'Jegy.hu',
    logo: '/jegy.png',
    description: 'Magyarország vezető online jegyértékesítő platformja.',
    website: 'https://jegy.hu',
    founded: 2007,
    headquarters: 'Budapest, Magyarország',
    rating: 4.7,
    features: ['Azonnali e-jegy', 'Mobil jegyek', 'Biztonságos fizetés'],
    countries: 1,
    verified: true,
  },
  {
    id: 'eventim-hu',
    name: 'Eventim Magyarország',
    logo: '/eventim.svg',
    description: 'A nemzetközi Eventim csoport magyar képviselete.',
    website: 'https://eventim.hu',
    founded: 2010,
    headquarters: 'Budapest, Magyarország',
    rating: 4.6,
    features: ['Nemzetközi események', 'Mobil applikáció', 'Biztonságos vásárlás'],
    countries: 21,
    verified: true,
  },
  {
    id: 'tixa',
    name: 'Tixa',
    logo: '/ff1c3722-2648-473e-8bb5-8d683a8e1d89.jpeg',
    description: 'Modern magyar jegyértékesítő platform.',
    website: 'https://tixa.hu',
    founded: 2015,
    headquarters: 'Budapest, Magyarország',
    rating: 4.5,
    features: ['Egyszerű felület', 'Gyors vásárlás', 'Magyar ügyfélszolgálat'],
    countries: 1,
    verified: true,
  },
  {
    id: 'jegymester',
    name: 'Jegymester',
    logo: '/jmhu-white.png',
    description: 'Kultúrális és szórakoztató események jegyértékesítője.',
    website: 'https://jegymester.hu',
    founded: 2005,
    headquarters: 'Budapest, Magyarország',
    rating: 4.4,
    features: ['Kulturális fókusz', 'Személyre szabott ajánlatok', 'Hűségprogram'],
    countries: 1,
    verified: true,
  },
  {
    id: 'ticketportal',
    name: 'TicketPortal',
    logo: '/logo-ticketportal-2023-blue.svg',
    description: 'Magyarországi és nemzetközi események jegyértékesítője.',
    website: 'https://www.ticketportal.hu',
    founded: 2001,
    headquarters: 'Budapest, Magyarország',
    rating: 4.5,
    features: ['Online jegyvásárlás', 'Mobil jegyek', 'Széles kínálat'],
    countries: 3,
    verified: true,
  },
]
// </CHANGE>

export const mockEvents: Event[] = [
  // KONCERTEK (10 events)
  {
    id: 1,
    name: 'Koncz Zsuzsa - Jubileumi koncert',
    category: 'Koncertek',
    venue: 'Papp László Budapest Sportaréna',
    city: 'Budapest',
    address: 'Stefánia út 2, 1143 Budapest',
    date: '2025-09-20',
    time: '19:00',
    doors: '18:00',
    image: '/legendary-hungarian-female-singer-concert-in-budap.jpg',
    description: 'Koncz Zsuzsa jubileumi koncertje a Sportarénában. A magyar könnyűzene legendája legnagyobb slágereivel.',
    faceValue: 8500,
    capacity: 12500,
  },
  {
    id: 2,
    name: 'Zorán - Aréna koncert',
    category: 'Koncertek',
    venue: 'Papp László Budapest Sportaréna',
    city: 'Budapest',
    address: 'Stefánia út 2, 1143 Budapest',
    date: '2025-10-15',
    time: '20:00',
    doors: '18:30',
    image: '/hungarian-rock-legend-male-singer-concert-budapest.jpg',
    description: 'Zorán aréna koncertje! Az örökzöld slágerek egy este: Az Ünnep, A Holló, Apám Hitte...',
    faceValue: 9500,
    capacity: 12500,
  },
  {
    id: 3,
    name: 'Magna Cum Laude - 30 éves jubileum',
    category: 'Koncertek',
    venue: 'MVM Dome',
    city: 'Budapest',
    address: 'Stefánia út 2, 1143 Budapest',
    date: '2025-11-22',
    time: '19:30',
    doors: '18:00',
    image: '/hungarian-rock-band-anniversary-concert-dome-stadi.jpg',
    description: 'A Magna Cum Laude 30 éves jubileumi koncertje! Háromórás show a legnagyobb slágerekkel.',
    faceValue: 11000,
    capacity: 20022,
  },
  {
    id: 4,
    name: 'Republic - Aréna turné',
    category: 'Koncertek',
    venue: 'Papp László Budapest Sportaréna',
    city: 'Budapest',
    address: 'Stefánia út 2, 1143 Budapest',
    date: '2025-08-30',
    time: '20:00',
    doors: '18:30',
    image: '/hungarian-rock-band-republic-concert-arena-budapes.jpg',
    description: 'A Republic aréna koncertje! Magyar rockzene csúcsformában, minden idők legnagyobb slágereivel.',
    faceValue: 10500,
    capacity: 12500,
  },
  {
    id: 5,
    name: 'Szandi és Boggie - Duett koncert',
    category: 'Koncertek',
    venue: 'Barba Negra Music Club',
    city: 'Budapest',
    address: 'Prielle Kornélia u. 4, 1117 Budapest',
    date: '2025-07-18',
    time: '19:00',
    doors: '18:00',
    image: '/two-female-singers-duet-concert-music-club-budapes.jpg',
    description: 'Két generáció, két hangszín - Szandi és Boggie közös koncertje a legjobb magyar slágerekkel.',
    faceValue: 6500,
    capacity: 1500,
  },
  {
    id: 6,
    name: 'Ákos - Szabadság koncert',
    category: 'Koncertek',
    venue: 'Papp László Budapest Sportaréna',
    city: 'Budapest',
    address: 'Stefánia út 2, 1143 Budapest',
    date: '2025-12-28',
    time: '19:00',
    doors: '17:30',
    image: '/hungarian-pop-icon-male-singer-arena-concert-freed.jpg',
    description: 'Ákos Szabadság koncertje! A magyar popzene ikonja, lenyűgöző show-val és örökzöld dalokkal.',
    faceValue: 12500,
    capacity: 12500,
  },
  {
    id: 7,
    name: 'Ed Sheeran - Budapest koncert',
    category: 'Koncertek',
    venue: 'Puskás Aréna',
    city: 'Budapest',
    address: 'Istvánmezei út 3-5, 1146 Budapest',
    date: '2025-06-25',
    time: '19:30',
    doors: '17:00',
    image: '/ed-sheeran-concert-stadium-puskas-arena-budapest-g.jpg',
    description: 'Ed Sheeran visszatér Budapestre! A brit szupersztár Mathematics turnéja a Puskás Arénában.',
    faceValue: 18500,
    capacity: 67215,
  },
  {
    id: 8,
    name: 'Coldplay - Music of the Spheres',
    category: 'Koncertek',
    venue: 'Puskás Aréna',
    city: 'Budapest',
    address: 'Istvánmezei út 3-5, 1146 Budapest',
    date: '2025-07-10',
    time: '19:00',
    doors: '17:00',
    image: '/coldplay-concert-stadium-colorful-lights-confetti-.jpg',
    description: 'Coldplay spektakuláris show-ja Budapesten! LED karperecek, konfetti és a legnagyobb slágerek.',
    faceValue: 19500,
    capacity: 67215,
  },
  {
    id: 9,
    name: 'Charlie Puth - One Night Only Budapest',
    category: 'Koncertek',
    venue: 'MVM Dome',
    city: 'Budapest',
    address: 'Stefánia út 2, 1143 Budapest',
    date: '2025-09-05',
    time: '20:00',
    doors: '18:30',
    image: '/charlie-puth-pop-singer-concert-piano-modern-stage.jpg',
    description: 'Charlie Puth exkluzív budapesti koncertje! Egyetlen este az amerikai popsztárral.',
    faceValue: 15500,
    capacity: 20022,
  },
  {
    id: 10,
    name: 'Bikini - 45 éves jubileum',
    category: 'Koncertek',
    venue: 'Barba Negra Music Club',
    city: 'Budapest',
    address: 'Prielle Kornélia u. 4, 1117 Budapest',
    date: '2025-11-08',
    time: '19:30',
    doors: '18:00',
    image: '/hungarian-rock-band-bikini-anniversary-concert-clu.jpg',
    description: 'A Bikini 45 éves jubileumi koncertje! Magyar rockzene klasszikusok: Egyszerű Dal, Nem vagyok már gyerek...',
    faceValue: 7500,
    capacity: 1500,
  },

  // SPORT - LABDARÚGÁS (8 events)
  {
    id: 11,
    name: 'Ferencváros - Újpest: Örökrangadó',
    category: 'Sport',
    venue: 'Groupama Aréna',
    city: 'Budapest',
    address: 'Üllői út 129, 1091 Budapest',
    date: '2025-10-12',
    time: '18:00',
    doors: '16:00',
    image: '/hungarian-football-derby-ferencvaros-groupama-aren.jpg',
    description: 'Az örökrangadó! Ferencváros - Újpest, a magyar labdarúgás legnagyobb derbije a Groupama Arénában.',
    faceValue: 6500,
    capacity: 23698,
  },
  {
    id: 12,
    name: 'Magyarország - Anglia: Barátságos mérkőzés',
    category: 'Sport',
    venue: 'Puskás Aréna',
    city: 'Budapest',
    address: 'Istvánmezei út 3-5, 1146 Budapest',
    date: '2025-09-09',
    time: '20:45',
    doors: '18:30',
    image: '/hungary-england-football-match-puskas-arena-budape.jpg',
    description: 'A magyar válogatott fogadja az angolokat! Történelmi mérkőzés a Puskás Arénában.',
    faceValue: 8500,
    capacity: 67215,
  },
  {
    id: 13,
    name: 'Ferencváros - Paks: NB I rangadó',
    category: 'Sport',
    venue: 'Groupama Aréna',
    city: 'Budapest',
    address: 'Üllői út 129, 1091 Budapest',
    date: '2025-11-20',
    time: '17:00',
    doors: '15:00',
    image: '/hungarian-league-football-match-groupama-arena-fer.jpg',
    description: 'NB I csúcsmérkőzés! A Ferencváros fogadja a Paksot a bajnoki címért folytatott harcban.',
    faceValue: 4500,
    capacity: 23698,
  },
  {
    id: 14,
    name: 'MTK Budapest - Diósgyőr: NB I',
    category: 'Sport',
    venue: 'Hidegkuti Nándor Stadion',
    city: 'Budapest',
    address: 'Salgótarjáni út 12-14, 1087 Budapest',
    date: '2025-08-16',
    time: '19:30',
    doors: '17:30',
    image: '/mtk-budapest-football-stadium-match-blue-white-hun.jpg',
    description: 'MTK Budapest hazai meccse a Hidegkuti Stadionban. Klasszikus NB I összecsapás.',
    faceValue: 3500,
    capacity: 5322,
  },
  {
    id: 15,
    name: 'Debrecen - Ferencváros: NB I',
    category: 'Sport',
    venue: 'Nagyerdei Stadion',
    city: 'Debrecen',
    address: 'Oláh Gábor u. 5, 4032 Debrecen',
    date: '2025-10-25',
    time: '16:00',
    doors: '14:00',
    image: '/debrecen-football-stadium-nagyerdei-hungarian-leag.jpg',
    description: 'Vidéki rangadó! A Debrecen hazai pályán fogadja a Ferencvárost. Telt ház várható.',
    faceValue: 5500,
    capacity: 20340,
  },
  {
    id: 16,
    name: 'Magyarország - Szerbia: Nemzetek Ligája',
    category: 'Sport',
    venue: 'Puskás Aréna',
    city: 'Budapest',
    address: 'Istvánmezei út 3-5, 1146 Budapest',
    date: '2025-11-15',
    time: '20:45',
    doors: '18:30',
    image: '/hungary-vs-serbia-football-match-puskas-arena-buda.jpg',
    description: 'Nemzetek Ligája mérkőzés! Magyarország - Szerbia, a továbbjutásért folyó küzdelem.',
    faceValue: 7500,
    capacity: 67215,
  },
  {
    id: 17,
    name: 'Honvéd - Újpest: Budapesti derbi',
    category: 'Sport',
    venue: 'Bozsik Aréna',
    city: 'Budapest',
    address: 'Bozsik József Stadion, Üllői út 129, 1091 Budapest',
    date: '2025-09-28',
    time: '17:30',
    doors: '15:30',
    image: '/budapest-football-derby-honved-vs-ujpest-bozsik-ar.jpg',
    description: 'Budapesti derbi! Honvéd - Újpest, a főváros két hagyományos csapatának összecsapása.',
    faceValue: 4000,
    capacity: 8200,
  },
  {
    id: 18,
    name: 'Magyarország - Németország: Eb-selejtező',
    category: 'Sport',
    venue: 'Puskás Aréna',
    city: 'Budapest',
    address: 'Istvánmezei út 3-5, 1146 Budapest',
    date: '2025-06-14',
    time: '20:45',
    doors: '18:30',
    image: '/hungary-vs-germany-football-euro-qualifier-puskas-.jpg',
    description: 'Európa-bajnoki selejtező! Magyarország - Németország, óriási tét az Eb-részvételért.',
    faceValue: 9500,
    capacity: 67215,
  },

  // SZÍNHÁZ & MUSICAL (6 events)
  {
    id: 19,
    name: 'A Nyomorultak - Musical',
    category: 'Színház',
    venue: 'Madách Színház',
    city: 'Budapest',
    address: 'Erzsébet krt. 31-33, 1073 Budapest',
    date: '2025-09-15',
    time: '19:00',
    doors: '18:00',
    image: '/les-miserables-musical-theater-stage-dramatic-ligh.jpg',
    description: 'A világhírű musical magyarul! Victor Hugo örökzöld története lenyűgöző előadásban.',
    faceValue: 12500,
    capacity: 1200,
  },
  {
    id: 20,
    name: 'Macskák - Musical',
    category: 'Színház',
    venue: 'Madách Színház',
    city: 'Budapest',
    address: 'Erzsébet krt. 31-33, 1073 Budapest',
    date: '2025-10-20',
    time: '19:30',
    doors: '18:30',
    image: '/cats-musical-theater-stage-performers-in-cat-costu.jpg',
    description: 'Andrew Lloyd Webber világhírű musicale Budapesten! A Macskák visszatér a magyar színpadra.',
    faceValue: 11500,
    capacity: 1200,
  },
  {
    id: 21,
    name: 'János Vitéz - Rockopera',
    category: 'Színház',
    venue: 'Erkel Színház',
    city: 'Budapest',
    address: 'Köztársaság tér 30, 1081 Budapest',
    date: '2025-11-10',
    time: '19:00',
    doors: '18:00',
    image: '/hungarian-rock-opera-janos-vitez-theater-stage-fol.jpg',
    description: 'A legendás magyar rockopera! Petőfi Sándor művéből készült örökbecsű előadás.',
    faceValue: 9500,
    capacity: 1837,
  },
  {
    id: 22,
    name: 'István, a király - Rockopera',
    category: 'Színház',
    venue: 'Papp László Budapest Sportaréna',
    city: 'Budapest',
    address: 'Stefánia út 2, 1143 Budapest',
    date: '2025-08-20',
    time: '20:00',
    doors: '18:00',
    image: '/hungarian-rock-opera-stephen-the-king-arena-show-s.jpg',
    description: 'Augusztus 20-i különleges előadás! A magyar rockopera csúcsműve az arénában.',
    faceValue: 15500,
    capacity: 12500,
  },
  {
    id: 23,
    name: 'Egy szerelem három éjszakája - Musical',
    category: 'Színház',
    venue: 'Operettszínház',
    city: 'Budapest',
    address: 'Nagymező u. 17, 1065 Budapest',
    date: '2025-09-25',
    time: '19:00',
    doors: '18:00',
    image: '/hungarian-romantic-musical-theater-stage-elegant-s.jpg',
    description: 'Presser Gábor és Sztevanovity Dusán musicale. Magyar könnyűzene slágerek színpadon.',
    faceValue: 8500,
    capacity: 999,
  },
  {
    id: 24,
    name: 'A dzsungel könyve - Gyerek musical',
    category: 'Színház',
    venue: 'Madách Színház',
    city: 'Budapest',
    address: 'Erzsébet krt. 31-33, 1073 Budapest',
    date: '2025-07-12',
    time: '15:00',
    doors: '14:00',
    image: '/jungle-book-musical-children-theater-colorful-cost.jpg',
    description: 'Családi musical élőben! Maugli kalandjai a magyar színpadon, gyerekeknek és felnőtteknek.',
    faceValue: 6500,
    capacity: 1200,
  },

  // STAND-UP & COMEDY (3 events)
  {
    id: 25,
    name: 'Dombóvári István - Stand up',
    category: 'Komédia',
    venue: 'Akvárium Klub',
    city: 'Budapest',
    address: 'Erzsébet tér 12, 1051 Budapest',
    date: '2025-10-08',
    time: '20:00',
    doors: '19:00',
    image: '/hungarian-stand-up-comedy-show-comedian-on-stage-w.jpg',
    description: 'Dombóvári István önálló estje! A magyar stand up comedy egyik legnagyobb alakja.',
    faceValue: 4500,
    capacity: 1500,
  },
  {
    id: 26,
    name: 'Szabó Balázs Bandája - Stand up show',
    category: 'Komédia',
    venue: 'MOM Kulturális Központ',
    city: 'Budapest',
    address: 'Csörsz u. 18, 1124 Budapest',
    date: '2025-11-18',
    time: '19:30',
    doors: '18:30',
    image: '/hungarian-comedy-show-multiple-comedians-on-stage-.jpg',
    description: 'Szabó Balázs Bandája vendégekkel! Stand up comedy est a legjobb magyar humoristákkal.',
    faceValue: 5500,
    capacity: 450,
  },
  {
    id: 27,
    name: 'Hadházi László - Aréna show',
    category: 'Komédia',
    venue: 'Papp László Budapest Sportaréna',
    city: 'Budapest',
    address: 'Stefánia út 2, 1143 Budapest',
    date: '2025-12-15',
    time: '19:00',
    doors: '17:30',
    image: '/hungarian-comedian-arena-show-large-stage-massive-.jpg',
    description: 'Hadházi László aréna show-ja! Magyarország egyik legnépszerűbb humoristája óriás produkcióban.',
    faceValue: 7500,
    capacity: 12500,
  },

  // FESZTIVÁLOK (3 events)
  {
    id: 28,
    name: 'Sziget Fesztivál - 5 napos bérlet',
    category: 'Fesztivál',
    venue: 'Óbudai-sziget',
    city: 'Budapest',
    address: 'Óbudai-sziget, 1033 Budapest',
    date: '2025-08-06',
    time: '12:00',
    doors: '10:00',
    image: '/sziget-festival-budapest-music-festival-main-stage.jpg',
    description: 'A Sziget Fesztivál 5 napos bérleteivel! Európa egyik legnagyobb zenei fesztiválja.',
    faceValue: 95000,
    capacity: 95000,
  },
  {
    id: 29,
    name: 'VOLT Fesztivál - Teljes bérlet',
    category: 'Fesztivál',
    venue: 'Lővér Kemping',
    city: 'Sopron',
    address: 'Lővér Kemping, 9400 Sopron',
    date: '2025-06-25',
    time: '14:00',
    doors: '12:00',
    image: '/volt-festival-sopron-hungary-outdoor-music-festiva.jpg',
    description: 'VOLT Fesztivál Sopronban! 4 nap alatt a legjobb magyar és nemzetközi előadók.',
    faceValue: 52000,
    capacity: 30000,
  },
  {
    id: 30,
    name: 'Balaton Sound - 5 napos bérlet',
    category: 'Fesztivál',
    venue: 'Zamárdi',
    city: 'Zamárdi',
    address: 'Balaton-part, 8621 Zamárdi',
    date: '2025-07-02',
    time: '16:00',
    doors: '14:00',
    image: '/balaton-sound-festival-lake-balaton-hungary-electr.jpg',
    description: 'Balaton Sound elektronikus zenei fesztivál! 5 nap a Balaton partján a legjobb DJ-kkel.',
    faceValue: 68000,
    capacity: 25000,
  },
]
// </CHANGE>

export const mockOffers: Record<number, TicketOffer[]> = {
  1: [
    {
      id: 'offer-1-1',
      eventId: 1,
      partner: mockPartners[0],
      section: 'Alsó szint',
      row: '25. sor',
      quantity: 2,
      price: 9200,
      totalPrice: 18400,
      fees: 1840,
      currency: 'HUF',
      delivery: 'E-jegy',
      url: 'https://jegy.hu/example',
      rating: 4.7,
      verified: true,
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 'offer-1-2',
      eventId: 1,
      partner: mockPartners[1],
      section: 'Alsó szint',
      row: '22. sor',
      quantity: 2,
      price: 9500,
      totalPrice: 19000,
      fees: 1900,
      currency: 'HUF',
      delivery: 'E-jegy',
      url: 'https://interticket.hu/example',
      rating: 4.6,
      verified: true,
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 'offer-1-3',
      eventId: 1,
      partner: mockPartners[2],
      section: 'Felső szint',
      row: '15. sor',
      quantity: 2,
      price: 10200,
      totalPrice: 20400,
      fees: 2040,
      currency: 'HUF',
      delivery: 'E-jegy',
      url: 'https://ticketexpress.hu/example',
      rating: 4.5,
      verified: true,
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 'offer-1-4',
      eventId: 1,
      partner: mockPartners[3],
      section: 'Álló',
      row: 'Belső tér',
      quantity: 4,
      price: 8800,
      totalPrice: 35200,
      fees: 3520,
      currency: 'HUF',
      delivery: 'E-jegy',
      url: 'https://eventim.hu/example',
      rating: 4.6,
      verified: true,
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 'offer-1-5',
      eventId: 1,
      partner: mockPartners[4],
      section: 'Alsó szint közép',
      row: '20. sor',
      quantity: 2,
      price: 9400,
      totalPrice: 18800,
      fees: 1600,
      currency: 'HUF',
      delivery: 'E-jegy',
      url: 'https://stubhub.hu/example',
      rating: 4.3,
      verified: true,
      lastUpdated: new Date().toISOString(),
    },
  ],
}
